apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" (. | merge (dict "ResourceName" "migrations")) }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
data:
  DB_USERNAME: '{{ .Values.migrations.params.database.username | b64enc }}'
  DB_PASSWORD: '{{ .Values.migrations.params.database.password | b64enc }}'
