apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.fullname" (. | merge (dict "ResourceName" "migrations")) }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
data: {}
