apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
data:
  SECRET_JAVA_OPTIONS: '{{ .Values.main.params.secretJavaOptions | b64enc }}'
  DB_USERNAME: '{{ .Values.main.params.database.username | b64enc }}'
  DB_PASSWORD: '{{ .Values.main.params.database.password | b64enc }}'
  {{ if .Values.main.params.application.rabbitmq.enabled -}}
  APPLICATION_RABBITMQ_USERNAME: '{{ .Values.main.params.application.rabbitmq.username | b64enc }}'
  APPLICATION_RABBITMQ_PASSWORD: '{{ .Values.main.params.application.rabbitmq.password | b64enc }}'
  {{- end }}
  {{ range $index, $element := .Values.main.params.extraSecretEnv }}
  {{- $index }}: '{{ $element | b64enc -}}'
  {{ end -}}

