apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    targetPort: http
    protocol: TCP
    port: 80
  - name: syslog
    targetPort: syslog
    protocol: UDP
    port: 514
